version: '3.2'

services:

  server:
    build:
      context: server
    ports:
      - '80'
    volumes:
      - '../:/var/www'
    depends_on:
      - db
    links:
      - db
    restart: always

  db:
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - '3306'
    volumes:
      - './db/data:/var/lib/mysql'
    restart: always